-- Conectar al contenedor correcto
ALTER SESSION SET CONTAINER = XEPDB1;

-- Crear usuario
CREATE USER TIENDAJAVA IDENTIFIED BY oracle123 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CONNECT, RESOURCE TO TIENDAJAVA;
GRANT ALL PRIVILEGES TO TIENDAJAVA;

-- Conectar como TIENDAJAVA y ejecutar el resto
CREATE TABLE USUARIO (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY,
    USERNAME    VARCHAR2(20)  NOT NULL,
    CONTRASENA  VARCHAR2(20)  NOT NULL,
    TIPO        VARCHAR2(20)  NOT NULL,
    CONSTRAINT PK_USUARIO          PRIMARY KEY (ID),
    CONSTRAINT UQ_USUARIO_USERNAME UNIQUE (USERNAME),
    CONSTRAINT CK_USUARIO_TIPO     CHECK (TIPO IN ('administrador', 'cliente'))
);

CREATE TABLE PRODUCTO (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY,
    DESCRIPCION VARCHAR2(100) NOT NULL,
    STOCK       NUMBER        NOT NULL,
    PRECIO      NUMBER(10,2)  NOT NULL,
    CONSTRAINT PK_PRODUCTO        PRIMARY KEY (ID),
    CONSTRAINT CK_PRODUCTO_STOCK  CHECK (STOCK >= 0),
    CONSTRAINT CK_PRODUCTO_PRECIO CHECK (PRECIO >= 0)
);

CREATE TABLE LINEA_COMPRA (
    ID_USUARIO  NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD    NUMBER NOT NULL,
    CONSTRAINT PK_CARRITO          PRIMARY KEY (ID_USUARIO, ID_PRODUCTO),
    CONSTRAINT FK_CARRITO_USUARIO  FOREIGN KEY (ID_USUARIO)  REFERENCES USUARIO(ID),
    CONSTRAINT FK_CARRITO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID),
    CONSTRAINT CK_CARRITO_CANTIDAD CHECK (CANTIDAD > 0)
);

CREATE TABLE GANANCIA (
    TOTAL               NUMBER(10,2) NOT NULL,
    ULTIMA_MODIFICACION DATE         NOT NULL,
    CONSTRAINT CK_GANANCIA_TOTAL CHECK (TOTAL >= 0)
);

INSERT INTO GANANCIA (TOTAL, ULTIMA_MODIFICACION)
VALUES (0, SYSDATE);
COMMIT;

INSERT INTO USUARIO (USERNAME, CONTRASENA, TIPO)
VALUES ('admin', 'admin123', 'administrador');
COMMIT;
